In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [18]:
data_csv = pd.read_csv("data.csv")
#print(data_csv)
data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [6]:
bedroom = data_csv['bedrooms']
bathroom = data_csv['bathrooms']
luas = data_csv['sqft_living']
floor = data_csv['floors']
prices = data_csv['price']
print(bedroom)


0       3.0
1       5.0
2       3.0
3       3.0
4       4.0
       ... 
4595    3.0
4596    3.0
4597    3.0
4598    4.0
4599    3.0
Name: bedrooms, Length: 4600, dtype: float64


In [ ]:
house_all = []
for index in range(len(bedroom)):
    house = []
    house.append(bedroom[index])
    house.append(bathroom[index])
    house.append(luas[index])
    house.append(floor[index])

    house_all.append(house)

print(house_all)

In [8]:
house_all = np.array(house_all)
prices = np.array(prices)

print(house_all)

[[3.00e+00 1.50e+00 1.34e+03 1.50e+00]
 [5.00e+00 2.50e+00 3.65e+03 2.00e+00]
 [3.00e+00 2.00e+00 1.93e+03 1.00e+00]
 ...
 [3.00e+00 2.50e+00 3.01e+03 2.00e+00]
 [4.00e+00 2.00e+00 2.09e+03 1.00e+00]
 [3.00e+00 2.50e+00 1.49e+03 2.00e+00]]


In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, input_shape=[4]) #input_s = input: bedroom, bathroom, luas, floor
])


In [11]:
model.compile(
    loss = 'mae',
    optimizer = 'sgd',
    metrics = 'accuracy'
)

In [12]:
model.fit(
    house_all, prices, epochs=100
)

Epoch 1/100
144/144 [==============================] - 1s 2ms/step - loss: 197568.0625 - accuracy: 0.0000e+00
Epoch 2/100
144/144 [==============================] - 0s 2ms/step - loss: 183873.3281 - accuracy: 0.0000e+00
Epoch 3/100
144/144 [==============================] - 0s 2ms/step - loss: 183680.1406 - accuracy: 0.0000e+00
Epoch 4/100
144/144 [==============================] - 0s 2ms/step - loss: 183957.2500 - accuracy: 0.0000e+00
Epoch 5/100
144/144 [==============================] - 0s 2ms/step - loss: 183921.3438 - accuracy: 0.0000e+00
Epoch 6/100
144/144 [==============================] - 0s 2ms/step - loss: 184060.5938 - accuracy: 0.0000e+00
Epoch 7/100
144/144 [==============================] - 0s 2ms/step - loss: 183812.3750 - accuracy: 0.0000e+00
Epoch 8/100
144/144 [==============================] - 0s 2ms/step - loss: 183719.3594 - accuracy: 0.0000e+00
Epoch 9/100
144/144 [==============================] - 0s 2ms/step - loss: 184028.6562 - accuracy: 0.0000e+00
Epoch 10/1

In [13]:
#model.predict([(bedroom, bathroom, luas, floor)])
predict_price = model.predict([(2, 1, 1250, 2)])
print(predict_price)

[[293329.03]]


In [ ]:
model.save("tes.h5")